apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-invoke
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        #image: nanajanashia/argocd-app:1.1
        #image: image-registry.openshift-image-registry.svc:5000/demo/sonarqube-example-git
        image: image-registry.openshift-image-registry.svc:5000/demo/test1
        ports:
        - containerPort: 8080
